### PR TITLE
Book theme docs

### PR DESCRIPTION
**Pull request by nvaytet**
Counterpart to https://github.com/scipp/scipp/pull/2233

### CODE REVIEW

**Comment by nvaytet** [comment]
@SimonHeybrock @jl-wynen  I can't approve my own PR, but this looks good to me.

**Comment by nvaytet** [comment]
> Matplotlib plots don't show, do I need to install something locally to make it work again?

Is that still the case for you? Did you try to reload the page in your browser?

**Comment by SimonHeybrock** [comment]
Let's just try... it works for scipp, after all?

**Review by SimonHeybrock — APPROVED** [review]

**Comment by jl-wynen** [comment]
> Is that still the case for you? Did you try to reload the page in your browser?

Yes. I tried in a fresh environment. I still have the problem. And also in scipp.

**Pull request merged**
